# Generated by Django 5.0.6 on 2024-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
