# Generated by Django 5.0.6 on 2024-06-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carrusel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
